#ifndef Command_H
#define Command_H

const char COMMAND_STOP = 'q';
const char COMMAND_ROTATE_FRONT_CW = 'F';
const char COMMAND_ROTATE_FRONT_CCW = 'f';
const char COMMAND_ROTATE_RIGHT_CW = 'R';
const char COMMAND_ROTATE_RIGHT_CCW = 'r';
const char COMMAND_ROTATE_LEFT_CW = 'L';
const char COMMAND_ROTATE_LEFT_CCW = 'l';
const char COMMAND_ROTATE_BACK_CW = 'B';
const char COMMAND_ROTATE_BACK_CCW = 'b';
const char COMMAND_MOVE_FRONT_FORWARD = 'S';
const char COMMAND_MOVE_FRONT_BACKWARD = 's';
const char COMMAND_MOVE_RIGHT_FORWARD = 'D';
const char COMMAND_MOVE_RIGHT_BACKWARD = 'd';
const char COMMAND_MOVE_LEFT_FORWARD = 'A';
const char COMMAND_MOVE_LEFT_BACKWARD = 'a';
const char COMMAND_MOVE_BACK_FORWARD = 'W';
const char COMMAND_MOVE_BACK_BACKWARD = 'w';
const char COMMAND_ESTABLISH_CONNECTION = '?';

const char validCommands[] = {
    COMMAND_STOP,
    COMMAND_ROTATE_FRONT_CW,
    COMMAND_ROTATE_FRONT_CCW,
    COMMAND_ROTATE_RIGHT_CW,
    COMMAND_ROTATE_RIGHT_CCW,
    COMMAND_ROTATE_LEFT_CW,
    COMMAND_ROTATE_LEFT_CCW,
    COMMAND_ROTATE_BACK_CW,
    COMMAND_ROTATE_BACK_CCW,
    COMMAND_MOVE_FRONT_FORWARD,
    COMMAND_MOVE_FRONT_BACKWARD,
    COMMAND_MOVE_RIGHT_FORWARD,
    COMMAND_MOVE_RIGHT_BACKWARD,
    COMMAND_MOVE_LEFT_FORWARD,
    COMMAND_MOVE_LEFT_BACKWARD,
    COMMAND_MOVE_BACK_FORWARD,
    COMMAND_MOVE_BACK_BACKWARD,
    COMMAND_ESTABLISH_CONNECTION,
};
#endif // Command_H